import type { ChallengeSeed } from './types';

export const LEARNING_PATHS = [
  { slug: 'sql-foundations', title: 'SQL Foundations', difficulty: 'BEGINNER' as const, color: '#4ade80' },
  { slug: 'sql-aggregates', title: 'Aggregates & Grouping', difficulty: 'BEGINNER' as const, color: '#fb923c' },
  { slug: 'sql-joins', title: 'Joins & Relationships', difficulty: 'INTERMEDIATE' as const, color: '#60a5fa' },
  { slug: 'sql-subqueries', title: 'Subqueries & CTEs', difficulty: 'INTERMEDIATE' as const, color: '#a78bfa' },
  { slug: 'sql-advanced', title: 'Advanced SQL', difficulty: 'ADVANCED' as const, color: '#f472b6' },
];

export const CHALLENGE_SEEDS: ChallengeSeed[] = [
  // --- TRACK 1: FOUNDATIONS (sql-foundations) ---
  {
    legacyId: 'f1', slug: 'select-everything', title: 'Select Everything', concept: 'SELECT',
    instructions: 'Retrieve every row and column from the employees table.',
    difficulty: 'BEGINNER', dialect: 'SQLITE', xpReward: 10, pathSlug: 'sql-foundations', moduleTitle: 'Getting Started',
    hints: [{ level: 1, content: 'SELECT * FROM employees; — the * means "all columns".' }],
    validationRules: [
      { type: 'ROW_COUNT', config: { exact: 5 } },
      { type: 'TABLE_USAGE', config: { tables: ['employees'] } },
    ],
    solution: 'SELECT * FROM employees;',
    successMsg: 'All 5 employees returned!', errorMsg: 'Try SELECT * FROM employees; — you should see 5 rows.',
    isPremium: false,
    aiPrompt: 'Explain the SQL SELECT statement to a complete beginner in under 80 words.',
  },
  {
    legacyId: 'f2', slug: 'pick-specific-columns', title: 'Pick Specific Columns', concept: 'SELECT columns',
    instructions: 'Show only the name and hire_date columns from the employees table.',
    difficulty: 'BEGINNER', dialect: 'SQLITE', xpReward: 10, pathSlug: 'sql-foundations', moduleTitle: 'Getting Started',
    hints: [{ level: 1, content: 'SELECT name, hire_date FROM employees;' }],
    validationRules: [
      { type: 'ROW_COUNT', config: { exact: 5 } },
      { type: 'COLUMN_NAMES', config: { columns: ['name', 'hire_date'], forbidden: ['id', 'dept_id'] } },
    ],
    solution: 'SELECT name, hire_date FROM employees;',
    successMsg: 'Only name and hire_date columns shown!', errorMsg: 'Select only name and hire_date, all 5 rows.',
    isPremium: false,
  },
  {
    legacyId: 'f3', slug: 'filter-with-where', title: 'Filter with WHERE', concept: 'WHERE',
    instructions: 'Find only the employees who work in department 1 (Engineering).',
    difficulty: 'BEGINNER', dialect: 'SQLITE', xpReward: 15, pathSlug: 'sql-foundations', moduleTitle: 'Filtering',
    hints: [{ level: 1, content: 'Add WHERE dept_id = 1 after your FROM clause.' }],
    validationRules: [
      { type: 'ROW_COUNT', config: { exact: 3 } },
      { type: 'KEYWORD_REQUIRED', config: { keyword: 'WHERE' } },
    ],
    solution: 'SELECT * FROM employees WHERE dept_id = 1;',
    successMsg: '3 engineers found!', errorMsg: 'Filter by dept_id = 1. Expect 3 results.',
    isPremium: false,
  },
  {
    legacyId: 'f4', slug: 'distinct-departments', title: 'Distinct Departments', concept: 'DISTINCT',
    instructions: 'Get a list of distinct department IDs that have employees.',
    difficulty: 'BEGINNER', dialect: 'SQLITE', xpReward: 15, pathSlug: 'sql-foundations', moduleTitle: 'Filtering',
    hints: [{ level: 1, content: 'Use SELECT DISTINCT dept_id FROM employees;' }],
    validationRules: [
      { type: 'ROW_COUNT', config: { exact: 3 } },
      { type: 'KEYWORD_REQUIRED', config: { keyword: 'DISTINCT' } },
      { type: 'COLUMN_NAMES', config: { columns: ['dept_id'] } },
    ],
    solution: 'SELECT DISTINCT dept_id FROM employees;',
    successMsg: 'Correct! Returned unique department IDs.', errorMsg: 'Use DISTINCT dept_id. Expect 3 unique ids.',
    isPremium: false,
  },
  {
    legacyId: 'f5', slug: 'filter-hire-date', title: 'Filter by Hire Date', concept: 'WHERE with Dates',
    instructions: 'Find all employees hired after January 1, 2020.',
    difficulty: 'BEGINNER', dialect: 'SQLITE', xpReward: 15, pathSlug: 'sql-foundations', moduleTitle: 'Filtering',
    hints: [{ level: 1, content: "Use hire_date > '2020-01-01' in your WHERE clause." }],
    validationRules: [
      { type: 'ROW_COUNT', config: { exact: 3 } },
      { type: 'KEYWORD_REQUIRED', config: { keyword: 'WHERE' } },
    ],
    solution: "SELECT * FROM employees WHERE hire_date > '2020-01-01';",
    successMsg: 'Found the 3 newer employees!', errorMsg: 'Compare hire_date with "2020-01-01".',
    isPremium: false,
  },
  {
    legacyId: 'f6', slug: 'filter-with-between', title: 'Filter with BETWEEN', concept: 'BETWEEN',
    instructions: 'Select all salaries where the amount is between 70000 and 95000 in the year 2023.',
    difficulty: 'BEGINNER', dialect: 'SQLITE', xpReward: 15, pathSlug: 'sql-foundations', moduleTitle: 'Filtering',
    hints: [{ level: 1, content: 'Use: WHERE amount BETWEEN 70000 AND 95000 AND year = 2023' }],
    validationRules: [
      { type: 'ROW_COUNT', config: { exact: 2 } },
      { type: 'KEYWORD_REQUIRED', config: { keyword: 'BETWEEN' } },
    ],
    solution: 'SELECT * FROM salaries WHERE amount BETWEEN 70000 AND 95000 AND year = 2023;',
    successMsg: 'Successfully filtered salaries between 70k and 95k for 2023!', errorMsg: 'Use BETWEEN for amount and filter year = 2023.',
    isPremium: false,
  },
  {
    legacyId: 'f7', slug: 'filter-with-in', title: 'Filter with IN', concept: 'IN',
    instructions: 'Find all employees who are in either department 2 or 3.',
    difficulty: 'BEGINNER', dialect: 'SQLITE', xpReward: 15, pathSlug: 'sql-foundations', moduleTitle: 'Filtering',
    hints: [{ level: 1, content: 'Use WHERE dept_id IN (2, 3)' }],
    validationRules: [
      { type: 'ROW_COUNT', config: { exact: 2 } },
      { type: 'KEYWORD_REQUIRED', config: { keyword: 'IN' } },
    ],
    solution: 'SELECT * FROM employees WHERE dept_id IN (2, 3);',
    successMsg: 'Found employees in departments 2 and 3!', errorMsg: 'Use IN (2, 3) to filter dept_id.',
    isPremium: false,
  },
  {
    legacyId: 'f8', slug: 'sort-results', title: 'Sort Results', concept: 'ORDER BY',
    instructions: 'List all employees sorted alphabetically by name (A → Z).',
    difficulty: 'BEGINNER', dialect: 'SQLITE', xpReward: 15, pathSlug: 'sql-foundations', moduleTitle: 'Sorting',
    hints: [{ level: 1, content: 'Add ORDER BY name ASC at the end.' }],
    validationRules: [
      { type: 'ROW_COUNT', config: { exact: 5 } },
      { type: 'SORT_ORDER', config: { column: 'name', direction: 'ASC' } },
    ],
    solution: 'SELECT * FROM employees ORDER BY name ASC;',
    successMsg: 'Alphabetical order confirmed!', errorMsg: 'Sort by name ASC.',
    isPremium: false,
  },
  {
    legacyId: 'f9', slug: 'limit-results', title: 'Limit Results', concept: 'LIMIT',
    instructions: 'Show only the first 3 employees when ordered alphabetically by name.',
    difficulty: 'BEGINNER', dialect: 'SQLITE', xpReward: 15, pathSlug: 'sql-foundations', moduleTitle: 'Sorting',
    hints: [{ level: 1, content: 'Add ORDER BY name ASC LIMIT 3;' }],
    validationRules: [
      { type: 'ROW_COUNT', config: { exact: 3 } },
      { type: 'KEYWORD_REQUIRED', config: { keyword: 'LIMIT' } },
      { type: 'SORT_ORDER', config: { column: 'name', direction: 'ASC' } },
    ],
    solution: 'SELECT * FROM employees ORDER BY name ASC LIMIT 3;',
    successMsg: 'LIMIT 3 works!', errorMsg: 'Order by name ASC and add LIMIT 3.',
    isPremium: false,
  },
  {
    legacyId: 'f10', slug: 'offset-results', title: 'Offset Results', concept: 'OFFSET',
    instructions: 'Show 2 employees, skipping the first 2, sorted by name alphabetically.',
    difficulty: 'BEGINNER', dialect: 'SQLITE', xpReward: 20, pathSlug: 'sql-foundations', moduleTitle: 'Sorting',
    hints: [{ level: 1, content: 'Use LIMIT 2 OFFSET 2 after ORDER BY name ASC.' }],
    validationRules: [
      { type: 'ROW_COUNT', config: { exact: 2 } },
      { type: 'KEYWORD_REQUIRED', config: { keyword: 'OFFSET' } },
      { type: 'SORT_ORDER', config: { column: 'name', direction: 'ASC' } },
    ],
    solution: 'SELECT * FROM employees ORDER BY name ASC LIMIT 2 OFFSET 2;',
    successMsg: 'OFFSET applied successfully!', errorMsg: 'Sort by name ASC, then apply LIMIT 2 OFFSET 2.',
    isPremium: false,
  },

  // --- TRACK 2: AGGREGATES (sql-aggregates) ---
  {
    legacyId: 'a11', slug: 'count-rows', title: 'Count Total Employees', concept: 'COUNT()',
    instructions: 'Count the total number of employees in the database. Alias the result as total_employees.',
    difficulty: 'BEGINNER', dialect: 'SQLITE', xpReward: 15, pathSlug: 'sql-aggregates', moduleTitle: 'Basic Aggregates',
    hints: [{ level: 1, content: 'SELECT COUNT(*) AS total_employees FROM employees;' }],
    validationRules: [
      { type: 'ROW_COUNT', config: { exact: 1 } },
      { type: 'KEYWORD_REQUIRED', config: { keyword: 'COUNT' } },
      { type: 'COLUMN_NAMES', config: { columns: ['total_employees'] } },
      { type: 'COLUMN_VALUES', config: { column: 'total_employees', values: [5] } },
    ],
    solution: 'SELECT COUNT(*) AS total_employees FROM employees;',
    successMsg: 'Correct! COUNT(*) returned 5.', errorMsg: 'Use COUNT(*) as total_employees.',
    isPremium: false,
  },
  {
    legacyId: 'a12', slug: 'sum-salaries', title: 'Sum Salaries', concept: 'SUM()',
    instructions: 'Calculate the sum of all salaries paid in 2024. Alias the result as total_budget.',
    difficulty: 'BEGINNER', dialect: 'SQLITE', xpReward: 15, pathSlug: 'sql-aggregates', moduleTitle: 'Basic Aggregates',
    hints: [{ level: 1, content: "SELECT SUM(amount) AS total_budget FROM salaries WHERE year = 2024;" }],
    validationRules: [
      { type: 'ROW_COUNT', config: { exact: 1 } },
      { type: 'COLUMN_NAMES', config: { columns: ['total_budget'] } },
      { type: 'COLUMN_VALUES', config: { column: 'total_budget', values: [470000] } },
    ],
    solution: 'SELECT SUM(amount) AS total_budget FROM salaries WHERE year = 2024;',
    successMsg: 'Sum is $470,000!', errorMsg: 'SUM(amount) WHERE year = 2024.',
    isPremium: false,
  },
  {
    legacyId: 'a13', slug: 'average-salary', title: 'Average Salary', concept: 'AVG()',
    instructions: 'Find the average salary across all employees for the year 2024. Alias the result as avg_salary.',
    difficulty: 'BEGINNER', dialect: 'SQLITE', xpReward: 20, pathSlug: 'sql-aggregates', moduleTitle: 'Basic Aggregates',
    hints: [{ level: 1, content: 'SELECT AVG(amount) AS avg_salary FROM salaries WHERE year = 2024;' }],
    validationRules: [
      { type: 'ROW_COUNT', config: { exact: 1 } },
      { type: 'COLUMN_NAMES', config: { columns: ['avg_salary'] } },
      { type: 'COLUMN_VALUES', config: { column: 'avg_salary', values: [94000] } },
    ],
    solution: 'SELECT AVG(amount) AS avg_salary FROM salaries WHERE year = 2024;',
    successMsg: 'Average is $94,000!', errorMsg: 'AVG(amount) for year 2024 should be 94000.',
    isPremium: false,
  },
  {
    legacyId: 'a14', slug: 'min-max-salary', title: 'Min and Max Salary', concept: 'MIN() & MAX()',
    instructions: 'Find the minimum and maximum salary amounts in the year 2024. Alias them as min_salary and max_salary.',
    difficulty: 'BEGINNER', dialect: 'SQLITE', xpReward: 20, pathSlug: 'sql-aggregates', moduleTitle: 'Basic Aggregates',
    hints: [{ level: 1, content: 'SELECT MIN(amount) AS min_salary, MAX(amount) AS max_salary FROM salaries WHERE year = 2024;' }],
    validationRules: [
      { type: 'ROW_COUNT', config: { exact: 1 } },
      { type: 'COLUMN_NAMES', config: { columns: ['min_salary', 'max_salary'] } },
      { type: 'COLUMN_VALUES', config: { column: 'min_salary', values: [71000] } },
      { type: 'COLUMN_VALUES', config: { column: 'max_salary', values: [120000] } },
    ],
    solution: 'SELECT MIN(amount) AS min_salary, MAX(amount) AS max_salary FROM salaries WHERE year = 2024;',
    successMsg: 'Min: $71,000, Max: $120,000!', errorMsg: 'Use MIN and MAX on amount column.',
    isPremium: false,
  },
  {
    legacyId: 'a15', slug: 'group-by-dept', title: 'Department Headcount', concept: 'GROUP BY',
    instructions: 'Count how many employees are in each department. Show dept_id and the headcount (alias headcount), sorted by headcount DESC.',
    difficulty: 'INTERMEDIATE', dialect: 'SQLITE', xpReward: 25, pathSlug: 'sql-aggregates', moduleTitle: 'Grouping',
    hints: [{ level: 1, content: 'SELECT dept_id, COUNT(*) AS headcount FROM employees GROUP BY dept_id ORDER BY headcount DESC;' }],
    validationRules: [
      { type: 'ROW_COUNT', config: { exact: 3 } },
      { type: 'KEYWORD_REQUIRED', config: { keyword: 'GROUP BY' } },
      { type: 'COLUMN_NAMES', config: { columns: ['dept_id', 'headcount'] } },
      { type: 'SORT_ORDER', config: { column: 'headcount', direction: 'DESC' } },
    ],
    solution: 'SELECT dept_id, COUNT(*) AS headcount FROM employees GROUP BY dept_id ORDER BY headcount DESC;',
    successMsg: 'Correctly grouped and sorted headcount!', errorMsg: 'GROUP BY dept_id and ORDER BY headcount DESC.',
    isPremium: false,
  },
  {
    legacyId: 'a16', slug: 'average-salary-by-year', title: 'Average Salary by Year', concept: 'GROUP BY',
    instructions: 'Show the average salary for each year in the salaries table. List the year and the average (alias avg_amount), sorted by year ASC.',
    difficulty: 'INTERMEDIATE', dialect: 'SQLITE', xpReward: 25, pathSlug: 'sql-aggregates', moduleTitle: 'Grouping',
    hints: [{ level: 1, content: 'SELECT year, AVG(amount) AS avg_amount FROM salaries GROUP BY year ORDER BY year ASC;' }],
    validationRules: [
      { type: 'ROW_COUNT', config: { exact: 3 } },
      { type: 'COLUMN_NAMES', config: { columns: ['year', 'avg_amount'] } },
      { type: 'SORT_ORDER', config: { column: 'year', direction: 'ASC' } },
    ],
    solution: 'SELECT year, AVG(amount) AS avg_amount FROM salaries GROUP BY year ORDER BY year ASC;',
    successMsg: 'Average salary per year calculated!', errorMsg: 'GROUP BY year and ORDER BY year ASC.',
    isPremium: false,
  },
  {
    legacyId: 'a17', slug: 'filter-groups-having', title: 'Filter Groups with HAVING', concept: 'HAVING',
    instructions: 'Find departments (dept_id) with more than 1 employee. Alias the count as num_employees.',
    difficulty: 'INTERMEDIATE', dialect: 'SQLITE', xpReward: 25, pathSlug: 'sql-aggregates', moduleTitle: 'Grouping',
    hints: [{ level: 1, content: 'SELECT dept_id, COUNT(*) AS num_employees FROM employees GROUP BY dept_id HAVING COUNT(*) > 1;' }],
    validationRules: [
      { type: 'ROW_COUNT', config: { exact: 1 } },
      { type: 'KEYWORD_REQUIRED', config: { keyword: 'HAVING' } },
      { type: 'COLUMN_VALUES', config: { column: 'dept_id', values: [1] } },
      { type: 'COLUMN_VALUES', config: { column: 'num_employees', values: [3] } },
    ],
    solution: 'SELECT dept_id, COUNT(*) AS num_employees FROM employees GROUP BY dept_id HAVING COUNT(*) > 1;',
    successMsg: 'Correct! Only department 1 has more than 1 employee.', errorMsg: 'Use HAVING to filter groups where COUNT(*) > 1.',
    isPremium: false,
  },
  {
    legacyId: 'a18', slug: 'having-avg-salary', title: 'High Average Salary Years', concept: 'HAVING',
    instructions: 'Find the years where the average salary across all employees exceeded $88,000. Alias the average as avg_salary.',
    difficulty: 'INTERMEDIATE', dialect: 'SQLITE', xpReward: 30, pathSlug: 'sql-aggregates', moduleTitle: 'Grouping',
    hints: [{ level: 1, content: 'SELECT year, AVG(amount) AS avg_salary FROM salaries GROUP BY year HAVING AVG(amount) > 88000;' }],
    validationRules: [
      { type: 'ROW_COUNT', config: { exact: 2 } },
      { type: 'KEYWORD_REQUIRED', config: { keyword: 'HAVING' } },
      { type: 'COLUMN_VALUES', config: { column: 'year', values: [2023, 2024] } },
    ],
    solution: 'SELECT year, AVG(amount) AS avg_salary FROM salaries GROUP BY year HAVING AVG(amount) > 88000;',
    successMsg: 'Found the high-average years!', errorMsg: 'Use HAVING AVG(amount) > 88000 after grouping.',
    isPremium: false,
  },

  // --- TRACK 3: JOINS (sql-joins) ---
  {
    legacyId: 'j19', slug: 'inner-join-customer-orders', title: 'Inner Join Customer Orders', concept: 'INNER JOIN',
    instructions: "List each order's id and total along with the customer's name. Sort by order id ASC.",
    difficulty: 'INTERMEDIATE', dialect: 'SQLITE', xpReward: 25, pathSlug: 'sql-joins', moduleTitle: 'Basic Joins',
    hints: [{ level: 1, content: 'SELECT o.id, o.total, c.name FROM orders o JOIN customers c ON o.customer_id = c.id ORDER BY o.id ASC;' }],
    validationRules: [
      { type: 'ROW_COUNT', config: { exact: 17 } },
      { type: 'KEYWORD_REQUIRED', config: { keyword: 'JOIN' } },
      { type: 'SORT_ORDER', config: { column: 'id', direction: 'ASC' } },
    ],
    solution: 'SELECT o.id, o.total, c.name FROM orders o JOIN customers c ON o.customer_id = c.id ORDER BY o.id ASC;',
    successMsg: 'Orders matched to customers!', errorMsg: 'INNER JOIN orders and customers on customer_id, sort by o.id ASC.',
    isPremium: false,
  },
  {
    legacyId: 'j20', slug: 'join-products-categories', title: 'Join Products and Categories', concept: 'JOIN',
    instructions: 'Show all products with their category names. Return product name, category name (alias category_name), and product price. Sort by product id ASC.',
    difficulty: 'INTERMEDIATE', dialect: 'SQLITE', xpReward: 25, pathSlug: 'sql-joins', moduleTitle: 'Basic Joins',
    hints: [{ level: 1, content: 'SELECT p.name, c.name AS category_name, p.price FROM products p JOIN categories c ON p.category_id = c.id ORDER BY p.id ASC;' }],
    validationRules: [
      { type: 'ROW_COUNT', config: { exact: 13 } },
      { type: 'COLUMN_NAMES', config: { columns: ['name', 'category_name', 'price'] } },
    ],
    solution: 'SELECT p.name, c.name AS category_name, p.price FROM products p JOIN categories c ON p.category_id = c.id ORDER BY p.id ASC;',
    successMsg: 'Products successfully joined with categories!', errorMsg: 'JOIN products to categories on category_id.',
    isPremium: false,
  },
  {
    legacyId: 'j21', slug: 'left-join-customers-orders', title: 'Left Join Customers & Orders', concept: 'LEFT JOIN',
    instructions: 'List all customer names and their order IDs (if any). Ensure customers with no orders are still listed. Sort by customer name ASC.',
    difficulty: 'INTERMEDIATE', dialect: 'SQLITE', xpReward: 30, pathSlug: 'sql-joins', moduleTitle: 'Outer Joins',
    hints: [{ level: 1, content: 'SELECT c.name, o.id AS order_id FROM customers c LEFT JOIN orders o ON c.id = o.customer_id ORDER BY c.name ASC;' }],
    validationRules: [
      { type: 'ROW_COUNT', config: { exact: 17 } }, // Wait! All 10 customers placed orders, so row count is still 17!
      { type: 'KEYWORD_REQUIRED', config: { keyword: 'LEFT JOIN' } },
    ],
    solution: 'SELECT c.name, o.id AS order_id FROM customers c LEFT JOIN orders o ON c.id = o.customer_id ORDER BY c.name ASC;',
    successMsg: 'Outer join returned all customers!', errorMsg: 'Use LEFT JOIN on customers and orders.',
    isPremium: false,
  },
  {
    legacyId: 'j22', slug: 'three-table-join', title: 'Join Three Tables', concept: 'Multi-table JOIN',
    instructions: 'Get a list of all order items for order #1. Show order_id, product name (alias product_name), qty, and unit_price. Sort by product name ASC.',
    difficulty: 'INTERMEDIATE', dialect: 'SQLITE', xpReward: 30, pathSlug: 'sql-joins', moduleTitle: 'Multi-table Joins',
    hints: [{ level: 1, content: 'JOIN order_items and products, filtering by order_id = 1.' }],
    validationRules: [
      { type: 'ROW_COUNT', config: { exact: 2 } },
      { type: 'TABLE_USAGE', config: { tables: ['order_items', 'products'] } },
      { type: 'COLUMN_NAMES', config: { columns: ['order_id', 'product_name', 'qty', 'unit_price'] } },
    ],
    solution: 'SELECT oi.order_id, p.name AS product_name, oi.qty, oi.unit_price FROM order_items oi JOIN products p ON oi.product_id = p.id WHERE oi.order_id = 1 ORDER BY product_name ASC;',
    successMsg: 'Order items retrieved with product names!', errorMsg: 'JOIN order_items and products, filter order_id = 1.',
    isPremium: false,
  },
  {
    legacyId: 'j23', slug: 'join-aggregate-orders', title: 'Customer Total Spending', concept: 'JOIN & Aggregation',
    instructions: 'Calculate the total amount spent by each customer. Return customer name and total_spent (alias total_spent), sorted by total_spent DESC.',
    difficulty: 'INTERMEDIATE', dialect: 'SQLITE', xpReward: 30, pathSlug: 'sql-joins', moduleTitle: 'Joins with Aggregates',
    hints: [{ level: 1, content: 'SELECT c.name, SUM(o.total) AS total_spent FROM customers c JOIN orders o ON c.id = o.customer_id GROUP BY c.name ORDER BY total_spent DESC;' }],
    validationRules: [
      { type: 'ROW_COUNT', config: { exact: 10 } },
      { type: 'KEYWORD_REQUIRED', config: { keyword: 'GROUP BY' } },
      { type: 'SORT_ORDER', config: { column: 'total_spent', direction: 'DESC' } },
    ],
    solution: 'SELECT c.name, SUM(o.total) AS total_spent FROM customers c JOIN orders o ON c.id = o.customer_id GROUP BY c.name ORDER BY total_spent DESC;',
    successMsg: 'Customer spend calculated and sorted!', errorMsg: 'JOIN customers to orders, GROUP BY customer name, SUM(o.total) DESC.',
    isPremium: false,
  },
  {
    legacyId: 'j24', slug: 'join-filter-chicago', title: 'Chicago Product Orders', concept: 'JOIN with Filter',
    instructions: "Find distinct products ordered by customers living in 'Chicago'. Return customer name, city, and product name. Sort by product name ASC.",
    difficulty: 'INTERMEDIATE', dialect: 'SQLITE', xpReward: 30, pathSlug: 'sql-joins', moduleTitle: 'Complex Filtering',
    hints: [{ level: 1, content: "Join customers, orders, order_items, and products. Add WHERE c.city = 'Chicago'." }],
    validationRules: [
      { type: 'ROW_COUNT', config: { exact: 4 } },
      { type: 'COLUMN_VALUES', config: { column: 'city', values: ['Chicago'] } },
    ],
    solution: "SELECT DISTINCT c.name, c.city, p.name AS product_name FROM customers c JOIN orders o ON c.id = o.customer_id JOIN order_items oi ON o.id = oi.order_id JOIN products p ON oi.product_id = p.id WHERE c.city = 'Chicago' ORDER BY product_name ASC;",
    successMsg: 'Found all Chicago orders!', errorMsg: 'Filter by city = "Chicago".',
    isPremium: false,
  },
  {
    legacyId: 'j25', slug: 'join-group-category-sales', title: 'Revenue by Category', concept: 'JOIN & Product Calculation',
    instructions: 'Calculate total revenue (sum of qty * unit_price, alias revenue) generated per product category. Show category name and revenue, sorted by revenue DESC.',
    difficulty: 'INTERMEDIATE', dialect: 'SQLITE', xpReward: 35, pathSlug: 'sql-joins', moduleTitle: 'Joins with Aggregates',
    hints: [{ level: 1, content: 'Join categories, products, and order_items. GROUP BY category name, SUM(qty * unit_price) DESC.' }],
    validationRules: [
      { type: 'ROW_COUNT', config: { exact: 5 } },
      { type: 'SORT_ORDER', config: { column: 'revenue', direction: 'DESC' } },
    ],
    solution: 'SELECT c.name, SUM(oi.qty * oi.unit_price) AS revenue FROM categories c JOIN products p ON c.id = p.category_id JOIN order_items oi ON p.id = oi.product_id GROUP BY c.name ORDER BY revenue DESC;',
    successMsg: 'Category revenue calculated!', errorMsg: 'Calculate SUM(qty * unit_price) grouped by category name.',
    isPremium: false,
  },
  {
    legacyId: 'j26', slug: 'join-having-active-cust', title: 'Highly Active Customers', concept: 'JOIN with HAVING',
    instructions: 'Find customers who have placed more than 2 orders. Show customer name and order_count (alias order_count), sorted by order_count DESC.',
    difficulty: 'INTERMEDIATE', dialect: 'SQLITE', xpReward: 35, pathSlug: 'sql-joins', moduleTitle: 'Joins with Aggregates',
    hints: [{ level: 1, content: 'Use HAVING COUNT(o.id) > 2 after grouping by customer name.' }],
    validationRules: [
      { type: 'ROW_COUNT', config: { exact: 1 } },
      { type: 'COLUMN_VALUES', config: { column: 'name', values: ['Alice Smith'] } },
    ],
    solution: 'SELECT c.name, COUNT(o.id) AS order_count FROM customers c JOIN orders o ON c.id = o.customer_id GROUP BY c.name HAVING COUNT(o.id) > 2 ORDER BY order_count DESC;',
    successMsg: 'Found customers with > 2 orders!', errorMsg: 'Filter grouped rows using HAVING count > 2.',
    isPremium: false,
  },
  {
    legacyId: 'j27', slug: 'cross-join-combinations', title: 'Cross Join Combinations', concept: 'CROSS JOIN',
    instructions: 'Produce a listing of every possible combination of customer name and category name. Sort by customer name ASC.',
    difficulty: 'INTERMEDIATE', dialect: 'SQLITE', xpReward: 35, pathSlug: 'sql-joins', moduleTitle: 'Advanced Joins',
    hints: [{ level: 1, content: 'SELECT c.name AS customer_name, cat.name AS category_name FROM customers c CROSS JOIN categories cat ORDER BY customer_name ASC;' }],
    validationRules: [
      { type: 'ROW_COUNT', config: { exact: 50 } },
      { type: 'KEYWORD_REQUIRED', config: { keyword: 'CROSS JOIN' } },
    ],
    solution: 'SELECT c.name AS customer_name, cat.name AS category_name FROM customers c CROSS JOIN categories cat ORDER BY customer_name ASC;',
    successMsg: 'CROSS JOIN completed successfully!', errorMsg: 'Use CROSS JOIN between customers and categories.',
    isPremium: false,
  },
  {
    legacyId: 'j28', slug: 'self-join-product-prices', title: 'Compare Product Prices', concept: 'SELF JOIN',
    instructions: 'Compare products: find pairs of products that have the exact same price. Return product 1 name (alias p1_name), product 2 name (alias p2_name), and their price. Avoid pairing a product with itself, and avoid duplicate pairings (e.g., show A-B but not B-A).',
    difficulty: 'INTERMEDIATE', dialect: 'SQLITE', xpReward: 35, pathSlug: 'sql-joins', moduleTitle: 'Advanced Joins',
    hints: [{ level: 1, content: 'JOIN products p1 with products p2 ON price. Use p1.id < p2.id to prevent duplicate pairs.' }],
    validationRules: [
      { type: 'ROW_COUNT', config: { exact: 2 } },
      { type: 'COLUMN_NAMES', config: { columns: ['p1_name', 'p2_name', 'price'] } },
    ],
    solution: 'SELECT p1.name AS p1_name, p2.name AS p2_name, p1.price FROM products p1 JOIN products p2 ON p1.price = p2.price AND p1.id < p2.id;',
    successMsg: 'Identified matching price pairs!', errorMsg: 'Self JOIN products on price, filter id comparison.',
    isPremium: false,
  },

  // --- TRACK 4: SUBQUERIES & CTES (sql-subqueries) ---
  {
    legacyId: 's29', slug: 'simple-scalar-subquery', title: 'Above Average Products', concept: 'Scalar Subquery',
    instructions: 'Find all products that cost more than the average product price. Return product name and price, sorted by price DESC.',
    difficulty: 'INTERMEDIATE', dialect: 'SQLITE', xpReward: 30, pathSlug: 'sql-subqueries', moduleTitle: 'Basic Subqueries',
    hints: [{ level: 1, content: 'WHERE price > (SELECT AVG(price) FROM products)' }],
    validationRules: [
      { type: 'ROW_COUNT', config: { exact: 2 } },
      { type: 'COLUMN_VALUES', config: { column: 'name', values: ['Laptop', 'Smartphone'] } },
    ],
    solution: 'SELECT name, price FROM products WHERE price > (SELECT AVG(price) FROM products) ORDER BY price DESC;',
    successMsg: 'Correctly subqueried average price!', errorMsg: 'Use subquery for average price in WHERE clause.',
    isPremium: false,
  },
  {
    legacyId: 's30', slug: 'subquery-in-clause', title: 'Cancelled Order Customers', concept: 'IN Subquery',
    instructions: "Select the names of customers who have at least one order with status 'Cancelled'.",
    difficulty: 'INTERMEDIATE', dialect: 'SQLITE', xpReward: 30, pathSlug: 'sql-subqueries', moduleTitle: 'Basic Subqueries',
    hints: [{ level: 1, content: "WHERE id IN (SELECT customer_id FROM orders WHERE status = 'Cancelled')" }],
    validationRules: [
      { type: 'ROW_COUNT', config: { exact: 1 } },
      { type: 'COLUMN_VALUES', config: { column: 'name', values: ['Hannah Abbott'] } },
    ],
    solution: "SELECT name FROM customers WHERE id IN (SELECT customer_id FROM orders WHERE status = 'Cancelled');",
    successMsg: 'Found customers with cancelled orders!', errorMsg: 'Use an IN subquery checking for Cancelled status.',
    isPremium: false,
  },
  {
    legacyId: 's31', slug: 'subquery-not-in-clause', title: 'Unordered Product Customers', concept: 'NOT IN Subquery',
    instructions: 'Find customers who have never placed an order. Return their name and email, sorted by name ASC.',
    difficulty: 'INTERMEDIATE', dialect: 'SQLITE', xpReward: 30, pathSlug: 'sql-subqueries', moduleTitle: 'Basic Subqueries',
    hints: [{ level: 1, content: 'WHERE id NOT IN (SELECT customer_id FROM orders WHERE customer_id IS NOT NULL)' }],
    validationRules: [
      { type: 'ROW_COUNT', config: { exact: 0 } }, // In this dataset all customers have orders, so returns 0
      { type: 'KEYWORD_REQUIRED', config: { keyword: 'NOT IN' } },
    ],
    solution: 'SELECT name, email FROM customers WHERE id NOT IN (SELECT DISTINCT customer_id FROM orders WHERE customer_id IS NOT NULL) ORDER BY name ASC;',
    successMsg: 'Empty list is correct as all customers have orders in this dataset!', errorMsg: 'Use NOT IN subquery pointing to orders.',
    isPremium: false,
  },
  {
    legacyId: 's32', slug: 'correlated-subquery-exists', title: 'Pending Order Check', concept: 'EXISTS',
    instructions: "Use EXISTS to find all customers who have placed a 'Pending' order.",
    difficulty: 'INTERMEDIATE', dialect: 'SQLITE', xpReward: 35, pathSlug: 'sql-subqueries', moduleTitle: 'Correlated Subqueries',
    hints: [{ level: 1, content: "WHERE EXISTS (SELECT 1 FROM orders WHERE customer_id = customers.id AND status = 'Pending')" }],
    validationRules: [
      { type: 'ROW_COUNT', config: { exact: 1 } },
      { type: 'KEYWORD_REQUIRED', config: { keyword: 'EXISTS' } },
      { type: 'COLUMN_VALUES', config: { column: 'name', values: ['Evan Wright'] } },
    ],
    solution: "SELECT c.name FROM customers c WHERE EXISTS (SELECT 1 FROM orders o WHERE o.customer_id = c.id AND o.status = 'Pending');",
    successMsg: 'EXISTS correlated subquery works!', errorMsg: 'Correlate using EXISTS in the WHERE clause.',
    isPremium: false,
  },
  {
    legacyId: 's33', slug: 'correlated-subquery-max', title: 'Most Expensive in Category', concept: 'Correlated Subquery',
    instructions: 'For each category, find the product(s) with the highest price. Show category_id, product name, and price, sorted by category_id ASC.',
    difficulty: 'INTERMEDIATE', dialect: 'SQLITE', xpReward: 35, pathSlug: 'sql-subqueries', moduleTitle: 'Correlated Subqueries',
    hints: [{ level: 1, content: 'WHERE p.price = (SELECT MAX(p2.price) FROM products p2 WHERE p2.category_id = p.category_id)' }],
    validationRules: [
      { type: 'ROW_COUNT', config: { exact: 5 } },
    ],
    solution: 'SELECT p.category_id, p.name, p.price FROM products p WHERE p.price = (SELECT MAX(p2.price) FROM products p2 WHERE p2.category_id = p.category_id) ORDER BY p.category_id ASC;',
    successMsg: 'Found most expensive products per category!', errorMsg: 'Filter price against a subquery calculating MAX(price) per category_id.',
    isPremium: false,
  },
  {
    legacyId: 's34', slug: 'simple-cte-basics', title: 'Completed Orders CTE', concept: 'CTE',
    instructions: "Create a CTE named active_orders that filters orders with status 'Completed'. Then, join this CTE with customers to show customer name and the completed order date. Sort by order_date ASC.",
    difficulty: 'INTERMEDIATE', dialect: 'SQLITE', xpReward: 35, pathSlug: 'sql-subqueries', moduleTitle: 'Common Table Expressions',
    hints: [{ level: 1, content: "WITH active_orders AS (SELECT customer_id, order_date FROM orders WHERE status = 'Completed') ..." }],
    validationRules: [
      { type: 'ROW_COUNT', config: { exact: 15 } },
      { type: 'KEYWORD_REQUIRED', config: { keyword: 'WITH' } },
    ],
    solution: "WITH active_orders AS (SELECT customer_id, order_date FROM orders WHERE status = 'Completed') SELECT c.name, ao.order_date FROM customers c JOIN active_orders ao ON c.id = ao.customer_id ORDER BY ao.order_date ASC;",
    successMsg: 'Completed orders retrieved via CTE!', errorMsg: 'Establish a WITH active_orders CTE first.',
    isPremium: false,
  },
  {
    legacyId: 's35', slug: 'multiple-cte-chain', title: 'High Spender Threshold', concept: 'Multiple CTEs',
    instructions: 'Use two CTEs: first (customer_spend) calculates total spend per customer. Second (avg_spend) calculates the average spend across all customers. Select customer names and their spend from customer_spend where total_spent exceeds the average spend. Sort by total_spent DESC.',
    difficulty: 'ADVANCED', dialect: 'SQLITE', xpReward: 40, pathSlug: 'sql-subqueries', moduleTitle: 'Common Table Expressions',
    hints: [{ level: 1, content: 'WITH customer_spend AS (...), avg_spend AS (...) SELECT ...' }],
    validationRules: [
      { type: 'ROW_COUNT', config: { exact: 4 } },
      { type: 'KEYWORD_REQUIRED', config: { keyword: 'WITH' } },
    ],
    solution: 'WITH customer_spend AS (SELECT customer_id, SUM(total) AS total_spent FROM orders GROUP BY customer_id), avg_spend AS (SELECT AVG(total_spent) AS average_spend FROM customer_spend) SELECT c.name, cs.total_spent FROM customers c JOIN customer_spend cs ON c.id = cs.customer_id JOIN avg_spend av ON cs.total_spent > av.average_spend ORDER BY cs.total_spent DESC;',
    successMsg: 'Successfully chained CTEs to filter top spending customers!', errorMsg: 'Define both CTEs in a single WITH statement separated by a comma.',
    isPremium: false,
  },
  {
    legacyId: 's36', slug: 'cte-product-sales-summary', title: 'Product Sales Summary', concept: 'LEFT JOIN & CTE',
    instructions: 'Use a CTE to calculate the total quantity sold for each product. Then query the products table and join the CTE to list product name, stock_qty, and total_sold (alias total_sold). Use COALESCE to show 0 if a product has never been sold. Sort by total_sold DESC.',
    difficulty: 'ADVANCED', dialect: 'SQLITE', xpReward: 40, pathSlug: 'sql-subqueries', moduleTitle: 'Common Table Expressions',
    hints: [{ level: 1, content: 'WITH product_sales AS (SELECT product_id, SUM(qty) AS total_sold FROM order_items GROUP BY product_id)...' }],
    validationRules: [
      { type: 'ROW_COUNT', config: { exact: 13 } },
      { type: 'KEYWORD_REQUIRED', config: { keyword: 'COALESCE' } },
    ],
    solution: 'WITH product_sales AS (SELECT product_id, SUM(qty) AS total_sold FROM order_items GROUP BY product_id) SELECT p.name, p.stock_qty, COALESCE(ps.total_sold, 0) AS total_sold FROM products p LEFT JOIN product_sales ps ON p.id = ps.product_id ORDER BY total_sold DESC;',
    successMsg: 'Product sales summarized with zero defaults!', errorMsg: 'Use LEFT JOIN and COALESCE(total_sold, 0).',
    isPremium: false,
  },
  {
    legacyId: 's37', slug: 'window-row-number', title: 'Product Price Ranks', concept: 'ROW_NUMBER()',
    instructions: 'Rank products within each category based on price (highest to lowest). Show category_id, product name, price, and price_rank (alias price_rank). Sort by category_id ASC, price_rank ASC.',
    difficulty: 'ADVANCED', dialect: 'SQLITE', xpReward: 40, pathSlug: 'sql-subqueries', moduleTitle: 'Window Functions',
    hints: [{ level: 1, content: 'Use ROW_NUMBER() OVER(PARTITION BY category_id ORDER BY price DESC)' }],
    validationRules: [
      { type: 'ROW_COUNT', config: { exact: 13 } },
      { type: 'KEYWORD_REQUIRED', config: { keyword: 'ROW_NUMBER' } },
    ],
    solution: 'SELECT category_id, name, price, ROW_NUMBER() OVER(PARTITION BY category_id ORDER BY price DESC) AS price_rank FROM products ORDER BY category_id ASC, price_rank ASC;',
    successMsg: 'Products ranked within categories!', errorMsg: 'Use ROW_NUMBER() OVER (PARTITION BY category_id ORDER BY price DESC).',
    isPremium: false,
  },
  {
    legacyId: 's38', slug: 'window-rank', title: 'Signup Order Rank', concept: 'RANK()',
    instructions: 'Rank all customers based on their signup_date (earliest to latest). Show customer name, signup_date, and signup_rank (alias signup_rank). Sort by signup_rank ASC.',
    difficulty: 'ADVANCED', dialect: 'SQLITE', xpReward: 40, pathSlug: 'sql-subqueries', moduleTitle: 'Window Functions',
    hints: [{ level: 1, content: 'Use RANK() OVER(ORDER BY signup_date ASC)' }],
    validationRules: [
      { type: 'ROW_COUNT', config: { exact: 10 } },
      { type: 'KEYWORD_REQUIRED', config: { keyword: 'RANK' } },
    ],
    solution: 'SELECT name, signup_date, RANK() OVER(ORDER BY signup_date ASC) AS signup_rank FROM customers ORDER BY signup_rank ASC;',
    successMsg: 'Customers ranked by signup date!', errorMsg: 'Use RANK() OVER (ORDER BY signup_date ASC).',
    isPremium: false,
  },
  {
    legacyId: 's39', slug: 'window-lead-lag', title: 'Previous Order Date', concept: 'LAG()',
    instructions: 'For customer #1, show each of their order dates and the date of their previous order (alias prev_order_date). Sort by order_date ASC.',
    difficulty: 'ADVANCED', dialect: 'SQLITE', xpReward: 40, pathSlug: 'sql-subqueries', moduleTitle: 'Window Functions',
    hints: [{ level: 1, content: 'Use LAG(order_date) OVER(ORDER BY order_date ASC) and filter customer_id = 1.' }],
    validationRules: [
      { type: 'ROW_COUNT', config: { exact: 3 } },
      { type: 'KEYWORD_REQUIRED', config: { keyword: 'LAG' } },
    ],
    solution: 'SELECT order_date, LAG(order_date) OVER(ORDER BY order_date ASC) AS prev_order_date FROM orders WHERE customer_id = 1 ORDER BY order_date ASC;',
    successMsg: 'Found previous order dates via LAG!', errorMsg: 'Use LAG window function ordered by order_date.',
    isPremium: false,
  },
  {
    legacyId: 's40', slug: 'conditional-case-when', title: 'Order Value Tiers', concept: 'CASE WHEN',
    instructions: "Classify orders based on their total amount: total >= 1000 is 'High Value', total >= 100 is 'Medium Value', otherwise 'Low Value'. Show order id, total, and value_tier (alias value_tier). Sort by total DESC.",
    difficulty: 'INTERMEDIATE', dialect: 'SQLITE', xpReward: 35, pathSlug: 'sql-subqueries', moduleTitle: 'Conditional Logic',
    hints: [{ level: 1, content: "Use CASE WHEN total >= 1000 THEN 'High Value' WHEN total >= 100 THEN ... END" }],
    validationRules: [
      { type: 'ROW_COUNT', config: { exact: 17 } },
      { type: 'KEYWORD_REQUIRED', config: { keyword: 'CASE' } },
    ],
    solution: "SELECT id, total, CASE WHEN total >= 1000 THEN 'High Value' WHEN total >= 100 THEN 'Medium Value' ELSE 'Low Value' END AS value_tier FROM orders ORDER BY total DESC;",
    successMsg: 'Orders tiered successfully!', errorMsg: 'Write a CASE expression mapping totals to tier strings.',
    isPremium: false,
  },

  // --- TRACK 5: ADVANCED SQL (sql-advanced) ---
  {
    legacyId: 'd41', slug: 'union-member-contacts', title: 'Unified Contact List', concept: 'UNION',
    instructions: "Create a list of all names and emails of library members, combined with names and dummy emails ('author@library.com') of authors. Sort the combined list by name ASC.",
    difficulty: 'ADVANCED', dialect: 'SQLITE', xpReward: 35, pathSlug: 'sql-advanced', moduleTitle: 'Set Operations',
    hints: [{ level: 1, content: "SELECT name, email FROM members UNION SELECT name, 'author@library.com' FROM authors ORDER BY name ASC;" }],
    validationRules: [
      { type: 'ROW_COUNT', config: { exact: 16 } },
      { type: 'KEYWORD_REQUIRED', config: { keyword: 'UNION' } },
    ],
    solution: "SELECT name, email FROM members UNION SELECT name, 'author@library.com' AS email FROM authors ORDER BY name ASC;",
    successMsg: 'Unified list generated via UNION!', errorMsg: 'Use UNION to combine the two queries.',
    isPremium: false,
  },
  {
    legacyId: 'd42', slug: 'intersect-borrowed-genres', title: 'Intersect Borrowed Genres', concept: 'INTERSECT',
    instructions: 'Find genres (names) that have books published before 1950, and also have books that have been loaned.',
    difficulty: 'ADVANCED', dialect: 'SQLITE', xpReward: 40, pathSlug: 'sql-advanced', moduleTitle: 'Set Operations',
    hints: [{ level: 1, content: 'Select genres with books < 1950, then INTERSECT with genres of books in loans.' }],
    validationRules: [
      { type: 'ROW_COUNT', config: { exact: 3 } },
      { type: 'KEYWORD_REQUIRED', config: { keyword: 'INTERSECT' } },
    ],
    solution: 'SELECT g.name FROM genres g JOIN books b ON g.id = b.genre_id WHERE b.published_year < 1950 INTERSECT SELECT g.name FROM genres g JOIN books b ON g.id = b.genre_id JOIN loans l ON b.id = l.book_id;',
    successMsg: 'Intersect matched genres correctly!', errorMsg: 'Use INTERSECT to find common items between two sets.',
    isPremium: false,
  },
  {
    legacyId: 'd43', slug: 'except-unborrowed-books', title: 'Never Borrowed Books', concept: 'EXCEPT',
    instructions: 'Find books (titles) that have never been borrowed. Use EXCEPT.',
    difficulty: 'ADVANCED', dialect: 'SQLITE', xpReward: 40, pathSlug: 'sql-advanced', moduleTitle: 'Set Operations',
    hints: [{ level: 1, content: 'SELECT title FROM books EXCEPT SELECT b.title FROM books b JOIN loans l ON b.id = l.book_id;' }],
    validationRules: [
      { type: 'ROW_COUNT', config: { exact: 3 } },
      { type: 'KEYWORD_REQUIRED', config: { keyword: 'EXCEPT' } },
    ],
    solution: 'SELECT title FROM books EXCEPT SELECT b.title FROM books b JOIN loans l ON b.id = l.book_id;',
    successMsg: 'Found books without loans!', errorMsg: 'Use EXCEPT to exclude borrowed book titles.',
    isPremium: false,
  },
  {
    legacyId: 'd44', slug: 'conditional-pivoting', title: 'Book Genre Counts Pivot', concept: 'CASE Pivot',
    instructions: "For each author, count how many books they have in 'Fiction' vs 'Classic' genres. Show author name, fiction_count (alias fiction_count), and classic_count (alias classic_count). Sort by author name ASC.",
    difficulty: 'ADVANCED', dialect: 'SQLITE', xpReward: 40, pathSlug: 'sql-advanced', moduleTitle: 'Advanced Aggregation',
    hints: [{ level: 1, content: "Use SUM(CASE WHEN g.name = 'Fiction' THEN 1 ELSE 0 END) AS fiction_count" }],
    validationRules: [
      { type: 'ROW_COUNT', config: { exact: 8 } },
      { type: 'KEYWORD_REQUIRED', config: { keyword: 'CASE' } },
    ],
    solution: "SELECT a.name, SUM(CASE WHEN g.name = 'Fiction' THEN 1 ELSE 0 END) AS fiction_count, SUM(CASE WHEN g.name = 'Classic' THEN 1 ELSE 0 END) AS classic_count FROM authors a LEFT JOIN books b ON a.id = b.author_id LEFT JOIN genres g ON b.genre_id = g.id GROUP BY a.name ORDER BY a.name ASC;",
    successMsg: 'Pivot results generated!', errorMsg: 'Use conditional SUM with CASE WHEN.',
    isPremium: false,
  },
  {
    legacyId: 'd45', slug: 'null-coalesce-loans', title: 'Loan Return Statuses', concept: 'COALESCE',
    instructions: "Show all loans with loan_date, return_date, and return_status (alias return_status). If return_date is NULL, display 'Still Out', otherwise display the return_date itself. Sort by loan id ASC.",
    difficulty: 'ADVANCED', dialect: 'SQLITE', xpReward: 35, pathSlug: 'sql-advanced', moduleTitle: 'Null Handling',
    hints: [{ level: 1, content: "COALESCE(return_date, 'Still Out') as return_status" }],
    validationRules: [
      { type: 'ROW_COUNT', config: { exact: 20 } },
      { type: 'KEYWORD_REQUIRED', config: { keyword: 'COALESCE' } },
    ],
    solution: "SELECT loan_date, return_date, COALESCE(return_date, 'Still Out') AS return_status FROM loans ORDER BY id ASC;",
    successMsg: 'Handled NULL return dates!', errorMsg: 'Use COALESCE to default NULL values to "Still Out".',
    isPremium: false,
  },
  {
    legacyId: 'd46', slug: 'date-difference-loans', title: 'Loan Durations', concept: 'Date Functions',
    instructions: 'Calculate the number of days each returned book was borrowed. Return loan id, book title, and borrow_duration (alias borrow_duration) in days. Exclude loans that are still out. Sort by borrow_duration DESC.',
    difficulty: 'ADVANCED', dialect: 'SQLITE', xpReward: 45, pathSlug: 'sql-advanced', moduleTitle: 'Date Math',
    hints: [{ level: 1, content: "Use strftime('%J', return_date) - strftime('%J', loan_date) and CAST to INTEGER." }],
    validationRules: [
      { type: 'ROW_COUNT', config: { exact: 15 } },
      { type: 'KEYWORD_REQUIRED', config: { keyword: 'strftime' } },
    ],
    solution: "SELECT l.id, b.title, CAST(strftime('%J', l.return_date) - strftime('%J', l.loan_date) AS INTEGER) AS borrow_duration FROM loans l JOIN books b ON l.book_id = b.id WHERE l.return_date IS NOT NULL ORDER BY borrow_duration DESC;",
    successMsg: 'Days calculations are correct!', errorMsg: 'Subtract strftime julian dates and cast as INTEGER.',
    isPremium: false,
  },
  {
    legacyId: 'd47', slug: 'overdue-books-search', title: 'Overdue Book Search', concept: 'Date Filtering',
    instructions: 'Find loans that were returned late (return_date > due_date). Return loan id, member name, book title, and days_late (alias days_late). Sort by days_late DESC.',
    difficulty: 'ADVANCED', dialect: 'SQLITE', xpReward: 45, pathSlug: 'sql-advanced', moduleTitle: 'Date Math',
    hints: [{ level: 1, content: "Compare return_date > due_date, and calculate days_late using strftime('%J')." }],
    validationRules: [
      { type: 'ROW_COUNT', config: { exact: 4 } },
      { type: 'COLUMN_VALUES', config: { column: 'days_late', values: [4, 3, 2, 1] } },
    ],
    solution: "SELECT l.id, m.name, b.title, CAST(strftime('%J', l.return_date) - strftime('%J', l.due_date) AS INTEGER) AS days_late FROM loans l JOIN members m ON l.member_id = m.id JOIN books b ON l.book_id = b.id WHERE l.return_date > l.due_date ORDER BY days_late DESC;",
    successMsg: 'Overdue loans detected!', errorMsg: 'Filter return_date > due_date and calculate days difference.',
    isPremium: false,
  },
  {
    legacyId: 'd48', slug: 'complex-window-dense-rank', title: 'Genre Inventory Ranks', concept: 'DENSE_RANK()',
    instructions: 'Rank books within each genre based on their available copies (highest availability first). If books have the same availability, they should share the rank. Show genre name, book title, copies_available, and avail_rank (alias avail_rank). Sort by genre name ASC, avail_rank ASC.',
    difficulty: 'ADVANCED', dialect: 'SQLITE', xpReward: 45, pathSlug: 'sql-advanced', moduleTitle: 'Window Functions',
    hints: [{ level: 1, content: 'Use DENSE_RANK() OVER(PARTITION BY genre_id ORDER BY copies_available DESC)' }],
    validationRules: [
      { type: 'ROW_COUNT', config: { exact: 13 } },
      { type: 'KEYWORD_REQUIRED', config: { keyword: 'DENSE_RANK' } },
    ],
    solution: 'SELECT g.name AS genre_name, b.title, b.copies_available, DENSE_RANK() OVER(PARTITION BY b.genre_id ORDER BY b.copies_available DESC) AS avail_rank FROM books b JOIN genres g ON b.genre_id = g.id ORDER BY genre_name ASC, avail_rank ASC;',
    successMsg: 'Inventory availability ranked via DENSE_RANK!', errorMsg: 'Use DENSE_RANK() OVER (PARTITION BY genre_id ORDER BY copies_available DESC).',
    isPremium: false,
  },
  {
    legacyId: 'd49', slug: 'multi-cte-library-stats', title: 'Top Library Borrowers', concept: 'Chained CTEs',
    instructions: 'Calculate library metrics: First CTE (member_loans) counts loans per member. Second CTE (max_loans) finds the maximum loans any member has. Join them to select the name(s) and loan_count (alias loan_count) of members who have borrowed the most books.',
    difficulty: 'ADVANCED', dialect: 'SQLITE', xpReward: 45, pathSlug: 'sql-advanced', moduleTitle: 'Common Table Expressions',
    hints: [{ level: 1, content: 'Define member_loans, then max_loans, and select members matching the max_loans value.' }],
    validationRules: [
      { type: 'ROW_COUNT', config: { exact: 2 } },
      { type: 'COLUMN_VALUES', config: { column: 'loan_count', values: [4] } },
    ],
    solution: 'WITH member_loans AS (SELECT member_id, COUNT(*) AS loan_count FROM loans GROUP BY member_id), max_loans AS (SELECT MAX(loan_count) AS max_l FROM member_loans) SELECT m.name, ml.loan_count FROM members m JOIN member_loans ml ON m.id = ml.member_id JOIN max_loans mx ON ml.loan_count = mx.max_l;',
    successMsg: 'Identified the most active library members!', errorMsg: 'Use two CTEs to find the max loan count and pull matching members.',
    isPremium: false,
  },
  {
    legacyId: 'd50', slug: 'recursive-hierarchy', title: 'Recursive Range Generator', concept: 'Recursive CTE',
    instructions: 'Generate a sequence of numbers from 1 to 5 using a recursive CTE. Name the table sequence and the column num.',
    difficulty: 'EXPERT', dialect: 'SQLITE', xpReward: 50, pathSlug: 'sql-advanced', moduleTitle: 'Common Table Expressions',
    hints: [{ level: 1, content: 'WITH RECURSIVE sequence(num) AS (SELECT 1 UNION ALL SELECT num + 1 FROM sequence WHERE num < 5)' }],
    validationRules: [
      { type: 'ROW_COUNT', config: { exact: 5 } },
      { type: 'KEYWORD_REQUIRED', config: { keyword: 'RECURSIVE' } },
      { type: 'COLUMN_VALUES', config: { column: 'num', values: [1, 2, 3, 4, 5] } },
    ],
    solution: 'WITH RECURSIVE sequence(num) AS (SELECT 1 UNION ALL SELECT num + 1 FROM sequence WHERE num < 5) SELECT num FROM sequence;',
    successMsg: 'Recursive range generated!', errorMsg: 'Use WITH RECURSIVE with UNION ALL incrementing the values.',
    isPremium: false,
  },
];

export const GUEST_CHALLENGE_SLUGS = ['select-everything', 'filter-with-where', 'count-rows'];

export function xpToLevel(xp: number): number {
  return Math.floor(Math.sqrt(xp / 100)) + 1;
}

export function levelTitle(level: number): string {
  const titles = ['Novice', 'Apprentice', 'Practitioner', 'Analyst', 'Expert', 'Master'];
  return titles[Math.min(level - 1, titles.length - 1)] ?? 'Master';
}
